### ISSUE TITLE
Help me translate the documentation

### ISSUE THREAD

**Issue by kelilipan** [ailabtelkom/id-NLP-resources#2]
add english version of this
![image](https://user-images.githubusercontent.com/35674157/94682294-ea68c800-034e-11eb-81dd-4bdce59af1f9.png)

**Comment by sunilgknair051** [comment]
Hi,
I think I can add translation for this piece of text, please assign and I will add it in readme.md

**Comment by muhsatrio** [comment]
Kindly check #8 @raisoturu

**Comment by muhsatrio** [comment]
I've updated the new commit as your feedback, please check @raisoturu, thank you! :)
